# Generated by Django 4.2.10 on 2024-03-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"managed": True, "verbose_name": "User Account", "verbose_name_plural": "Users Account"},
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=120, verbose_name="Country of Residency"),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=14, verbose_name="Mobile Number"),
        ),
        migrations.AddField(
            model_name="user",
            name="waitlisted",
            field=models.BooleanField(default=False, verbose_name="Waitlisted"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email Address"),
        ),
    ]
