# Generated by Django 4.2.10 on 2024-03-14 05:30

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_user_country_user_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activities",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("identity", models.CharField(max_length=255)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[("LOGIN", "LOGIN"), ("SINGUP", "SINGUP")], default="SINGUP", max_length=8
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "managed": True,
            },
        ),
    ]
